language: c++
notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
sudo: required
dist: trusty
services:
  - docker
env:
  global:
    - USE_DOCKER=true
  matrix:
    - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=true
    - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=false
    - ROS_DISTRO=kinetic   ROSWS=wstool BUILDER=catkin USE_DEB=true
    - ROS_DISTRO=kinetic   ROSWS=wstool BUILDER=catkin USE_DEB=false
matrix:
  allow_failures:
    - env: ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=false
    - env: ROS_DISTRO=kinetic   ROSWS=wstool BUILDER=catkin USE_DEB=false
script: source .travis/travis.sh
