Name:           ros-indigo-eusurdf
Version:        0.2.1
Release:        0%{?dist}
Summary:        ROS eusurdf package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/eusurdf
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-collada-urdf-jsk-patch
Requires:       ros-indigo-gazebo-ros
Requires:       ros-indigo-roseus
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-collada-urdf-jsk-patch
BuildRequires:  ros-indigo-euslisp
BuildRequires:  ros-indigo-rosbash

%description
urdf models converted from euslisp

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Nov 27 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 0.2.1-0
- Autogenerated by Bloom

* Thu Nov 26 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 0.2.0-0
- Autogenerated by Bloom

* Thu Nov 26 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 0.1.14-0
- Autogenerated by Bloom

* Mon Aug 31 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 0.1.13-0
- Autogenerated by Bloom

