Name:           ros-hydro-euscollada
Version:        0.1.13
Release:        0%{?dist}
Summary:        ROS euscollada package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/euscollada
Source0:        %{name}-%{version}.tar.gz

Requires:       collada-dom-devel
Requires:       qhull-devel
Requires:       ros-hydro-assimp-devel
Requires:       ros-hydro-collada-parser
Requires:       ros-hydro-collada-urdf
Requires:       ros-hydro-resource-retriever
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospack
Requires:       ros-hydro-tf
Requires:       ros-hydro-urdf
Requires:       ros-hydro-urdfdom
Requires:       yaml-cpp-devel
BuildRequires:  collada-dom-devel
BuildRequires:  qhull-devel
BuildRequires:  ros-hydro-assimp-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-collada-parser
BuildRequires:  ros-hydro-collada-urdf
BuildRequires:  ros-hydro-mk
BuildRequires:  ros-hydro-resource-retriever
BuildRequires:  ros-hydro-rosboost-cfg
BuildRequires:  ros-hydro-rosbuild
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospack
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-urdf
BuildRequires:  ros-hydro-urdfdom
BuildRequires:  yaml-cpp-devel

%description
euscollada

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Aug 31 2015 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.13-0
- Autogenerated by Bloom

* Thu May 07 2015 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.12-0
- Autogenerated by Bloom

* Thu Apr 09 2015 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.11-0
- Autogenerated by Bloom

* Thu Apr 02 2015 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.10-0
- Autogenerated by Bloom

* Thu Apr 02 2015 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.9-0
- Autogenerated by Bloom

* Wed Jan 07 2015 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.1.8-0
- Autogenerated by Bloom

