Name:           ros-melodic-euscollada
Version:        0.4.3
Release:        0%{?dist}
Summary:        ROS euscollada package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/euscollada
Source0:        %{name}-%{version}.tar.gz

Requires:       collada-dom-devel
Requires:       qhull-devel
Requires:       ros-melodic-assimp-devel
Requires:       ros-melodic-collada-parser
Requires:       ros-melodic-collada-urdf
Requires:       ros-melodic-resource-retriever
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rospack
Requires:       ros-melodic-rostest
Requires:       ros-melodic-tf
Requires:       ros-melodic-urdf
Requires:       urdfdom-devel
Requires:       yaml-cpp-devel
BuildRequires:  collada-dom-devel
BuildRequires:  qhull-devel
BuildRequires:  ros-melodic-assimp-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-collada-parser
BuildRequires:  ros-melodic-collada-urdf
BuildRequires:  ros-melodic-mk
BuildRequires:  ros-melodic-openhrp3
BuildRequires:  ros-melodic-pr2-description
BuildRequires:  ros-melodic-resource-retriever
BuildRequires:  ros-melodic-rosboost-cfg
BuildRequires:  ros-melodic-rosbuild
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roseus
BuildRequires:  ros-melodic-rospack
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-urdf
BuildRequires:  urdfdom-devel
BuildRequires:  yaml-cpp-devel

%description
euscollada

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Dec 05 2018 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.4.3-0
- Autogenerated by Bloom

