Name:           ros-kinetic-euscollada
Version:        0.3.3
Release:        1%{?dist}
Summary:        ROS euscollada package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/euscollada
Source0:        %{name}-%{version}.tar.gz

Requires:       collada-dom-devel
Requires:       qhull-devel
Requires:       ros-kinetic-assimp-devel
Requires:       ros-kinetic-collada-parser
Requires:       ros-kinetic-collada-urdf
Requires:       ros-kinetic-resource-retriever
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rospack
Requires:       ros-kinetic-rostest
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-urdf
Requires:       urdfdom-devel
Requires:       yaml-cpp-devel
BuildRequires:  collada-dom-devel
BuildRequires:  qhull-devel
BuildRequires:  ros-kinetic-assimp-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cmake-modules
BuildRequires:  ros-kinetic-collada-parser
BuildRequires:  ros-kinetic-collada-urdf
BuildRequires:  ros-kinetic-mk
BuildRequires:  ros-kinetic-openhrp3
BuildRequires:  ros-kinetic-pr2-description
BuildRequires:  ros-kinetic-resource-retriever
BuildRequires:  ros-kinetic-rosboost-cfg
BuildRequires:  ros-kinetic-rosbuild
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-roseus
BuildRequires:  ros-kinetic-rospack
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-urdf
BuildRequires:  urdfdom-devel
BuildRequires:  yaml-cpp-devel

%description
euscollada

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Feb 18 2017 Yohei Kakiuchi <youhei@jsk.t.u-tokyo.ac.jp> - 0.3.3-1
- Autogenerated by Bloom

